trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev

steps:

- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.Repository.LocalPath)/publish'
    verbose: true
  displayName: 'Install npm package'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.Repository.LocalPath)/publish'
    customCommand: 'run build validate $(Build.Repository.LocalPath) $(DataFactoryID)'
  displayName: 'Validate'