name: Deploy to Azure Data Factory

on:
  push:
    branches:
      - main
    paths:
      - 'pipeline/**/*'
      - '.github/workflows/**/*'
  workflow_dispatch:

jobs:
  build-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm packages 
      run: npm install
      working-directory: ${{github.workspace}}/work/build

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Pull ADF resources
      run: npm run build pull /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} ./work/
      working-directory: ${{ github.workspace }}
  
    - name: Create required directories and publish_config.json
      run: |
          mkdir -p ./work/pipeline ./work/dataset ./work/linkedService ./work/integrationRuntime
          echo '{"lastPublishedDate": "2024-01-01T00:00:00Z"}' > ./work/publish_config.json
  
    - name: Validate ARM template
      run: npm run build validate ${{github.workspace}}/work/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }}  # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/work/build

    - name: Generate ARM template
      run: npm run build export ${{github.workspace}}/work/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} "ExportedArmTemplate"
      working-directory: ${{github.workspace}}/work/build 

    - name: Upload ARM templates
      uses: actions/upload-artifact@v3
      with:
        name: arm-templates
        path: ./work/build/ArmTemplate/

  deploy-adf:
    needs: build-template
    runs-on: ubuntu-latest

    steps:
    - name: Download ARM templates
      uses: actions/download-artifact@v3
      with:
        name: arm-templates

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Stop triggers
      run: |
        pwsh ./github/workflows/script/manage_triggers.ps1 -armTemplate ./work/build/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $true
      shell: pwsh

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group "rg-eh-upskilling-eh-damian.r" --template-file ./work/build/ArmTemplate/ARMTemplateForFactory.json --parameters @./work/build/ArmTemplate/ARMTemplateParametersForFactory.json --parameters factoryName=$DataFactoryName

    - name: Start triggers
      run: |
        pwsh ./github/workflows/script/manage_triggers.ps1 -armTemplate ./work/build/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $false
      shell: pwsh