name: Deploy to Azure Data Factory

on:
  push:
    branches:
      - main
    paths:
      - 'pipeline/**/*'
      - '.github/workflows/**/*'
  workflow_dispatch:

jobs:
  build-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Ensure publish directory exists
      run: mkdir -p ./publish

    - name: Install npm packages 
      run: npm install
      working-directory: ./publish

    - name: Validate ARM template
      run: node node_modules/@microsoft/azure-data-factory-utilities/lib/index validate ./publish
      working-directory: ./publish

    - name: Generate ARM template
      run: npm run build export ./publish $DataFactoryID ArmTemplate
      working-directory: ./publish

    - name: Upload ARM templates
      uses: actions/upload-artifact@v3
      with:
        name: arm-templates
        path: ./publish/ArmTemplate/

  deploy-adf:
    needs: build-template
    runs-on: ubuntu-latest

    steps:
    - name: Download ARM templates
      uses: actions/download-artifact@v3
      with:
        name: arm-templates

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Stop triggers
      run: |
        pwsh ./github/workflows/script/manage_triggers.ps1 -armTemplate ./publish/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $true
      shell: pwsh

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group "rg-eh-upskilling-eh-damian.r" --template-file ./publish/ArmTemplate/ARMTemplateForFactory.json --parameters @./publish/ArmTemplate/ARMTemplateParametersForFactory.json --parameters factoryName=$DataFactoryName

    - name: Start triggers
      run: |
        pwsh ./github/workflows/script/manage_triggers.ps1 -armTemplate ./publish/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $false
      shell: pwsh