name: Deploy to Azure Data Factory

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Pobiera cale repo a nie ostatni commit
        submodules: true

    - name: Verify manage_triggers.ps1 existence
      run: |
        ls -l ${{ github.workspace }}/work/
        cat ${{ github.workspace }}/work/manage_triggers.ps1 || echo "File not found"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm packages 
      run: npm install
      working-directory: ${{github.workspace}}/work/build 

    - name: Validate ARM template
      run: npm run build validate ${{github.workspace}}/work/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }}  # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/work/build

    - name: Generate ARM template
      run: npm run build export ${{github.workspace}}/work/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} "ExportedArmTemplate"
      working-directory: ${{github.workspace}}/work/build

    - name: List generated files
      run: ls -R ${{github.workspace}}/work/build/ExportedArmTemplate

    - name: Fix permissions
      run: chmod -R 755 ${{github.workspace}}/work/build/ExportedArmTemplate

    - name: Create ExportedArmTemplate directory
      run: mkdir -p ${{github.workspace}}/work/build/ExportedArmTemplate

    - name: Upload ARM templates
      uses: actions/upload-artifact@v3
      with:
        name: ExportedArmTemplate
        path: ${{github.workspace}}/work/build/ExportedArmTemplate/**
        include-hidden-files: true

  deploy-adf:
    needs: build-template
    runs-on: ubuntu-latest

    steps:
    - name: Download ARM templates
      uses: actions/download-artifact@v3
      with:
        name: ExportedArmTemplate

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List all files
      run: ls -R ${{ github.workspace }}

    - name: Stop triggers
      run: |
        pwsh ${{github.workspace}}/work/manage_triggers.ps1 -armTemplate ${{github.workspace}}/work/build/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $true
      shell: pwsh
      env:
        DataFactoryName: ${{ secrets.ADF_NAME }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group "${{ secrets.RESOURCE_GROUP }}" --template-file ${{github.workspace}}/work/build/ArmTemplate/ARMTemplateForFactory.json --parameters ${{github.workspace}}/work/build/ArmTemplate/ARMTemplateParametersForFactory.json --parameters factoryName=$DataFactoryName

    - name: Start triggers
      run: |
        pwsh ${{github.workspace}}/work/manage_triggers.ps1 -armTemplate ${{github.workspace}}/work/build/ArmTemplate/ARMTemplateForFactory.json -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -DataFactoryName $DataFactoryName -predeployment $false
      shell: pwsh